---
- name: set nodebrew env
  copy: src=:etc:profile.d/nodebrew.sh dest=/etc/profile.d/nodebrew.sh mode=0755

- name: path
  shell: /etc/profile.d/nodebrew.sh

- name: is exist nodebrew
  shell: ls /usr/local/nodebrew/nodebrew; echo $?;
  register: is_exist_nodebrew

- name: get nodebrew
  shell: curl https://raw.githubusercontent.com/hokaccha/nodebrew/master/nodebrew | perl - setup
  when: is_exist_nodebrew.stdout != 0

- name: move nodebrew
  shell: mv /root/.nodebrew /usr/local/nodebrew
  when: is_exist_nodebrew.stdout != 0

- name: set nodebrew permission
  shell: chmod -R 777 /usr/local/nodebrew

- name: install default nodejs
  shell: NODEBREW_ROOT=/usr/local/nodebrew /usr/local/nodebrew/nodebrew install-binary {{ default_nodejs_version }}

- name: set default nodejs
  shell: NODEBREW_ROOT=/usr/local/nodebrew /usr/local/nodebrew/nodebrew use {{ default_nodejs_version }}
